version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./_docker/django/development/Dockerfile
    command: bash -c "pip3 install -r requirements.txt && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - 8000:8000
    restart: always
    #tty: true
    volumes:
      - "./backend:/var/www/backend"

  postgres:
    environment:
      - POSTGRES_USER=integreat
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=integreat
    image: postgres
    restart: always
    volumes:
      - "./_postgres:/var/lib/postgresql"
